export { supabase, isSupabaseConfigured } from './client'
export type { Database, CocinaSlug } from './types/database'
export * from './queries/productos'
export * from './queries/ordenes'
export * from './queries/menu'
export * from './queries/lealtad'
export * from './queries/empleados'
export * from './queries/inventario'
export * from './queries/promociones'
export * from './queries/auth'
