export { getSupabase, type ShakeClient } from './client'
export * from './queries/catalogo'
export * from './queries/costeo'
export * from './queries/ordenes'
export * from './queries/cocina'
export * from './queries/inventario'
export * from './queries/caja'
export * from './queries/reportes'
export * from './queries/clientes'
export * from './queries/lealtad'
